name: Continuous Integration

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      pgsql:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          PGPASSWORD: password
          POSTGRES_DB: testing
          POSTGRES_USER: sail
          POSTGRES_PASSWORD: password

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Copy .env
        run: cp .env.ci .env
      - name: Install composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Setup Project
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan key:generate
      - name: Run migrations
        run: |
          php artisan migrate
      - name: Compile assets
        run: |
          npm install
          npm run build
      - name: Run Unit tests
        run: php artisan test
